# Generated by Django 4.2.6 on 2025-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoomApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_id",
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
