# Generated by Django 4.2.6 on 2025-01-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RoomApp", "0004_alter_booking_room"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
