# Generated by Django 4.2.6 on 2025-01-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoomApp", "0005_delete_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("DELUXE", "Deluxe"),
                    ("SUITE", "Suite"),
                    ("FAMILY", "Family Room"),
                ],
                max_length=50,
            ),
        ),
    ]
