# Generated by Django 4.2.6 on 2025-01-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoomApp", "0006_alter_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
