# Generated by Django 4.2.6 on 2025-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoomApp", "0007_alter_room_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="rating",
            field=models.IntegerField(default=5),
        ),
    ]
