# Generated by Django 4.2.6 on 2025-02-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoomApp", "0008_room_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(default="nope"),
        ),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="nope", max_length=500),
        ),
    ]
