# Generated by Django 4.2.6 on 2025-01-25 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("HOUSEKEEPER", "Housekeeper"),
                            ("MANAGER", "Manager"),
                            ("RECEPTIONIST", "Receptionist"),
                        ],
                        default="USER",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
