# Generated by Django 4.2.6 on 2025-02-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0009_alter_booking_room_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
